// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4874598343565998864),
      name: 'GameMap',
      lastPropertyId: const obx_int.IdUid(5, 4649713973701547764),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2396658297608107797),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8777438224428614145),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 9113987160376593415),
            name: 'backgroundPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4649713973701547764),
            name: 'iconPath',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'layers', srcEntity: 'MapLayer', srcField: '')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1151296108528548671),
      name: 'Grenade',
      lastPropertyId: const obx_int.IdUid(13, 2224045878878249736),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1523532813895765735),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 950273212782284817),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1729191835908128596),
            name: 'type',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1600410473762697832),
            name: 'xRatio',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3876738248442041323),
            name: 'yRatio',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3130120832146975148),
            name: 'layerId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 1044355777290460145),
            relationTarget: 'MapLayer'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7481528315953036701),
            name: 'team',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4331277814055993411),
            name: 'isFavorite',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 306005704061569859),
            name: 'isNewImport',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6337261151973670656),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 2224045878878249736),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'steps', srcEntity: 'GrenadeStep', srcField: '')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 7522074683401753015),
      name: 'GrenadeStep',
      lastPropertyId: const obx_int.IdUid(7, 5080755458375743937),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4529193645252377659),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5080909842562114286),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8744430209968682788),
            name: 'stepIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5599090826804008928),
            name: 'grenadeId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 1724088102970475947),
            relationTarget: 'Grenade'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5080755458375743937),
            name: 'title',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'medias', srcEntity: 'StepMedia', srcField: '')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 3785369609838644109),
      name: 'MapLayer',
      lastPropertyId: const obx_int.IdUid(5, 6497300199794798600),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1998961404054032331),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7140953938581955735),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1559501678126514301),
            name: 'assetPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5111115788014308126),
            name: 'sortOrder',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6497300199794798600),
            name: 'mapId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 5029553932108087550),
            relationTarget: 'GameMap')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'grenades', srcEntity: 'Grenade', srcField: '')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 6381942963095217154),
      name: 'StepMedia',
      lastPropertyId: const obx_int.IdUid(4, 3844777532110758578),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1024229054021951815),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 179718448543168036),
            name: 'localPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5328492197248485886),
            name: 'type',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3844777532110758578),
            name: 'stepId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 9216007268719976428),
            relationTarget: 'GrenadeStep')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 6381942963095217154),
      lastIndexId: const obx_int.IdUid(5, 9216007268719976428),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [5937828641329526594],
      retiredPropertyUids: const [
        3280344576014643591,
        8482885107684588201,
        6110140661167916245,
        2730915328597924841,
        5861369385412327226
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    GameMap: obx_int.EntityDefinition<GameMap>(
        model: _entities[0],
        toOneRelations: (GameMap object) => [],
        toManyRelations: (GameMap object) => {
              obx_int.RelInfo<MapLayer>.toOneBacklink(
                      5, object.id, (MapLayer srcObject) => srcObject.map):
                  object.layers
            },
        getId: (GameMap object) => object.id,
        setId: (GameMap object, int id) {
          object.id = id;
        },
        objectToFB: (GameMap object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final backgroundPathOffset = fbb.writeString(object.backgroundPath);
          final iconPathOffset = fbb.writeString(object.iconPath);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(3, backgroundPathOffset);
          fbb.addOffset(4, iconPathOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final backgroundPathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final iconPathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = GameMap(
              name: nameParam,
              backgroundPath: backgroundPathParam,
              iconPath: iconPathParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<GameMap>(
              object.layers,
              store,
              obx_int.RelInfo<MapLayer>.toOneBacklink(
                  5, object.id, (MapLayer srcObject) => srcObject.map));
          return object;
        }),
    Grenade: obx_int.EntityDefinition<Grenade>(
        model: _entities[1],
        toOneRelations: (Grenade object) => [object.layer],
        toManyRelations: (Grenade object) => {
              obx_int.RelInfo<GrenadeStep>.toOneBacklink(5, object.id,
                  (GrenadeStep srcObject) => srcObject.grenade): object.steps
            },
        getId: (Grenade object) => object.id,
        setId: (Grenade object, int id) {
          object.id = id;
        },
        objectToFB: (Grenade object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addInt64(2, object.type);
          fbb.addFloat64(3, object.xRatio);
          fbb.addFloat64(4, object.yRatio);
          fbb.addInt64(7, object.layer.targetId);
          fbb.addInt64(8, object.team);
          fbb.addBool(9, object.isFavorite);
          fbb.addBool(10, object.isNewImport);
          fbb.addInt64(11, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(12, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final typeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final teamParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final isFavoriteParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 22, false);
          final isNewImportParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 24, false);
          final xRatioParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final yRatioParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = Grenade(
              title: titleParam,
              type: typeParam,
              team: teamParam,
              isFavorite: isFavoriteParam,
              isNewImport: isNewImportParam,
              xRatio: xRatioParam,
              yRatio: yRatioParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0))
            ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0));
          object.layer.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.layer.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Grenade>(
              object.steps,
              store,
              obx_int.RelInfo<GrenadeStep>.toOneBacklink(
                  5, object.id, (GrenadeStep srcObject) => srcObject.grenade));
          return object;
        }),
    GrenadeStep: obx_int.EntityDefinition<GrenadeStep>(
        model: _entities[2],
        toOneRelations: (GrenadeStep object) => [object.grenade],
        toManyRelations: (GrenadeStep object) => {
              obx_int.RelInfo<StepMedia>.toOneBacklink(
                      4, object.id, (StepMedia srcObject) => srcObject.step):
                  object.medias
            },
        getId: (GrenadeStep object) => object.id,
        setId: (GrenadeStep object, int id) {
          object.id = id;
        },
        objectToFB: (GrenadeStep object, fb.Builder fbb) {
          final descriptionOffset = fbb.writeString(object.description);
          final titleOffset = fbb.writeString(object.title);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, descriptionOffset);
          fbb.addInt64(3, object.stepIndex);
          fbb.addInt64(4, object.grenade.targetId);
          fbb.addOffset(6, titleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final stepIndexParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = GrenadeStep(
              title: titleParam,
              description: descriptionParam,
              stepIndex: stepIndexParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.grenade.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.grenade.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<GrenadeStep>(
              object.medias,
              store,
              obx_int.RelInfo<StepMedia>.toOneBacklink(
                  4, object.id, (StepMedia srcObject) => srcObject.step));
          return object;
        }),
    MapLayer: obx_int.EntityDefinition<MapLayer>(
        model: _entities[3],
        toOneRelations: (MapLayer object) => [object.map],
        toManyRelations: (MapLayer object) => {
              obx_int.RelInfo<Grenade>.toOneBacklink(
                      8, object.id, (Grenade srcObject) => srcObject.layer):
                  object.grenades
            },
        getId: (MapLayer object) => object.id,
        setId: (MapLayer object, int id) {
          object.id = id;
        },
        objectToFB: (MapLayer object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final assetPathOffset = fbb.writeString(object.assetPath);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, assetPathOffset);
          fbb.addInt64(3, object.sortOrder);
          fbb.addInt64(4, object.map.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final assetPathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final sortOrderParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = MapLayer(
              name: nameParam,
              assetPath: assetPathParam,
              sortOrder: sortOrderParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.map.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.map.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<MapLayer>(
              object.grenades,
              store,
              obx_int.RelInfo<Grenade>.toOneBacklink(
                  8, object.id, (Grenade srcObject) => srcObject.layer));
          return object;
        }),
    StepMedia: obx_int.EntityDefinition<StepMedia>(
        model: _entities[4],
        toOneRelations: (StepMedia object) => [object.step],
        toManyRelations: (StepMedia object) => {},
        getId: (StepMedia object) => object.id,
        setId: (StepMedia object, int id) {
          object.id = id;
        },
        objectToFB: (StepMedia object, fb.Builder fbb) {
          final localPathOffset = fbb.writeString(object.localPath);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, localPathOffset);
          fbb.addInt64(2, object.type);
          fbb.addInt64(3, object.step.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final localPathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final typeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final object = StepMedia(localPath: localPathParam, type: typeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.step.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.step.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [GameMap] entity fields to define ObjectBox queries.
class GameMap_ {
  /// See [GameMap.id].
  static final id =
      obx.QueryIntegerProperty<GameMap>(_entities[0].properties[0]);

  /// See [GameMap.name].
  static final name =
      obx.QueryStringProperty<GameMap>(_entities[0].properties[1]);

  /// See [GameMap.backgroundPath].
  static final backgroundPath =
      obx.QueryStringProperty<GameMap>(_entities[0].properties[2]);

  /// See [GameMap.iconPath].
  static final iconPath =
      obx.QueryStringProperty<GameMap>(_entities[0].properties[3]);

  /// see [GameMap.layers]
  static final layers =
      obx.QueryBacklinkToMany<MapLayer, GameMap>(MapLayer_.map);
}

/// [Grenade] entity fields to define ObjectBox queries.
class Grenade_ {
  /// See [Grenade.id].
  static final id =
      obx.QueryIntegerProperty<Grenade>(_entities[1].properties[0]);

  /// See [Grenade.title].
  static final title =
      obx.QueryStringProperty<Grenade>(_entities[1].properties[1]);

  /// See [Grenade.type].
  static final type =
      obx.QueryIntegerProperty<Grenade>(_entities[1].properties[2]);

  /// See [Grenade.xRatio].
  static final xRatio =
      obx.QueryDoubleProperty<Grenade>(_entities[1].properties[3]);

  /// See [Grenade.yRatio].
  static final yRatio =
      obx.QueryDoubleProperty<Grenade>(_entities[1].properties[4]);

  /// See [Grenade.layer].
  static final layer =
      obx.QueryRelationToOne<Grenade, MapLayer>(_entities[1].properties[5]);

  /// See [Grenade.team].
  static final team =
      obx.QueryIntegerProperty<Grenade>(_entities[1].properties[6]);

  /// See [Grenade.isFavorite].
  static final isFavorite =
      obx.QueryBooleanProperty<Grenade>(_entities[1].properties[7]);

  /// See [Grenade.isNewImport].
  static final isNewImport =
      obx.QueryBooleanProperty<Grenade>(_entities[1].properties[8]);

  /// See [Grenade.createdAt].
  static final createdAt =
      obx.QueryDateProperty<Grenade>(_entities[1].properties[9]);

  /// See [Grenade.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<Grenade>(_entities[1].properties[10]);

  /// see [Grenade.steps]
  static final steps =
      obx.QueryBacklinkToMany<GrenadeStep, Grenade>(GrenadeStep_.grenade);
}

/// [GrenadeStep] entity fields to define ObjectBox queries.
class GrenadeStep_ {
  /// See [GrenadeStep.id].
  static final id =
      obx.QueryIntegerProperty<GrenadeStep>(_entities[2].properties[0]);

  /// See [GrenadeStep.description].
  static final description =
      obx.QueryStringProperty<GrenadeStep>(_entities[2].properties[1]);

  /// See [GrenadeStep.stepIndex].
  static final stepIndex =
      obx.QueryIntegerProperty<GrenadeStep>(_entities[2].properties[2]);

  /// See [GrenadeStep.grenade].
  static final grenade =
      obx.QueryRelationToOne<GrenadeStep, Grenade>(_entities[2].properties[3]);

  /// See [GrenadeStep.title].
  static final title =
      obx.QueryStringProperty<GrenadeStep>(_entities[2].properties[4]);

  /// see [GrenadeStep.medias]
  static final medias =
      obx.QueryBacklinkToMany<StepMedia, GrenadeStep>(StepMedia_.step);
}

/// [MapLayer] entity fields to define ObjectBox queries.
class MapLayer_ {
  /// See [MapLayer.id].
  static final id =
      obx.QueryIntegerProperty<MapLayer>(_entities[3].properties[0]);

  /// See [MapLayer.name].
  static final name =
      obx.QueryStringProperty<MapLayer>(_entities[3].properties[1]);

  /// See [MapLayer.assetPath].
  static final assetPath =
      obx.QueryStringProperty<MapLayer>(_entities[3].properties[2]);

  /// See [MapLayer.sortOrder].
  static final sortOrder =
      obx.QueryIntegerProperty<MapLayer>(_entities[3].properties[3]);

  /// See [MapLayer.map].
  static final map =
      obx.QueryRelationToOne<MapLayer, GameMap>(_entities[3].properties[4]);

  /// see [MapLayer.grenades]
  static final grenades =
      obx.QueryBacklinkToMany<Grenade, MapLayer>(Grenade_.layer);
}

/// [StepMedia] entity fields to define ObjectBox queries.
class StepMedia_ {
  /// See [StepMedia.id].
  static final id =
      obx.QueryIntegerProperty<StepMedia>(_entities[4].properties[0]);

  /// See [StepMedia.localPath].
  static final localPath =
      obx.QueryStringProperty<StepMedia>(_entities[4].properties[1]);

  /// See [StepMedia.type].
  static final type =
      obx.QueryIntegerProperty<StepMedia>(_entities[4].properties[2]);

  /// See [StepMedia.step].
  static final step = obx.QueryRelationToOne<StepMedia, GrenadeStep>(
      _entities[4].properties[3]);
}
